MVCTutorials/Controllers/TestController.cs
using MVCTutorials.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCTutorials.Controllers
{
    
    public class TestController : Controller
    {
        [HttpGet]
        public string PrintPragim()
        {
            string s = "Pragim Technologies";
            return s;
           // message("hyd");
        }

        [HttpGet]
        public string message(string id1)
        {
           // int number = id;
            return "Hello Good Morning, :" +id1;
        }

        public string messageRoute()
        {
            
            return "Hello Good Moring, :"+RouteData.Values["id"];
        }

        public ViewResult Index()
        {
            ViewData["Name"] = "Pragim Technologies";
            ViewData["Location"] = "Hyderabad";
            ViewData["Today"] = DateTime.Now;
            ViewData["LayoutData"] = "Layout Data";
            ViewData["Title"] = "Index Title";

            ViewBag.VBName = "VB Pragim Technologies";
            ViewBag.VBToday = DateTime.Now;

           // string title = ViewData["Title"].ToString();


            return View();
        }
        public ViewResult About()
        {
            throw new Exception("error occured");
            ViewData["Title"] = "About Title";
            return View();
        }
       
        public ViewResult Contact()
        {
            return View();
        }
        public ActionResult Razor()
        {
            return View();
        }
        public ActionResult FullPage()
        {
            return View();
        }

        public ActionResult PartailView1()
        {
            return PartialView();
        }
        public ActionResult PartailView2()
        {
            // return PartialView("~/Views/Shared/PartailView2.cshtml");
            return PartialView();
        }

        [ChildActionOnly]
        public ActionResult PartailView3()
        {
            return PartialView();
        }
        [AllowAnonymous]
       // [OutputCache(Duration =10)]
        [LogFilter]
        public ActionResult GetDate()
        {
            Debug.WriteLine(DateTime.Now.ToString());
            return Content(DateTime.Now.ToString());
        }
        [HandleError]
        public  ActionResult Exception()
        {
            throw new Exception("This is sample exeption");
            return View();
        }
    }

    //  BaseClass (ActionResult) and Derived Class (ViewResult)
    // BaseClass b=new BaseClass();    // True
    // DerivedClass d=new DerivedClass();  // True
    // BaseClass b=new DerivedClass();   // True  ActionResult a=new ViewResult();
    // DerivedClass d=new BaseClass();   // False

}

MVCTutorials/Views/Test/About.cshtml
@{ 
    Layout = "~/Views/Shared/_TestLayout2.cshtml";
}
<h1> this is mahesh page</h1>

MVCTutorials/Views/Test/Contact.cshtml
@{
    Layout = "~/Views/Shared/_TestLayout2.cshtml";
}

<p class="mydiv">This is Contact Page</p>
<div class="mycolor">
    This is my color css class
    <br />
    <br />
    <br />
</div>
<div class="jumbotron">This is Big Block</div>

MVCTutorials/Views/Test/FullPage.cshtml
@{
    ViewBag.Title = "FullPage";
}

<h2>FullPage</h2>

<h4>Partail View 1</h4>

@* using partail in same controller*@
<div>
    @Html.Partial("PartailView1")
   
</div>

@*using render partail*@
<div>
    @{
        Html.RenderPartial("PartailView1");
     }
</div>

@* using partail in Shared folder*@
<div>
    @Html.Partial("PartailView2")

</div>

@* using partail with Html.Action*@
<div>
    <p>Using Html.Action</p>
    @Html.Action("PartailView3","Test")

</div>

@* using partail with Html.RenderAction*@
<div>
    <p>Using Html.RenderAction</p>
    @{
        Html.RenderAction("PartailView3", "Test");
    }

</div>

MVCTutorials/Views/Test/Index.cshtml
@{
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "Red",
        Value = "1"
    });
    listItems.Add(new SelectListItem
    {
        Text = "Yellow",
        Value = "2"
    });
    listItems.Add(new SelectListItem
    {
        Text = "Green",
        Value = "3"
    });
}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-3">
            This is left panel
        </div>
        <div class="col-md-9">


            <div>
                <div class="jumbotron">This is Big Block</div>
                <h2>This is First View Result</h2>
                <h4>Test message</h4>
                <button>Test Button</button>
                <button class="btn btn-warning">Test Button</button>
                <table class="table table-striped tabl-b">
                    <thead>
                        <tr>
                            <td>Header 1</td>
                            <td>Header 2</td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Row 1</td>
                            <td>Row 2</td>
                        </tr>
                        <tr>
                            <td>Row 1</td>
                            <td>Row 2</td>
                        </tr>
                    </tbody>
                </table>
                <h3>
                    ViewData:  @ViewData["Name"] <br />
                    ViewBag: @ViewBag.VBName
                </h3>

                <h3>
                    @ViewData["Location"]
                </h3>

                <h3>
                    ViewData Date: @(Convert.ToDateTime(ViewData["Today"]).DayOfWeek) <br />
                    ViewBag Date: @ViewBag.VBToday.DayOfWeek
                </h3>
                @Html.TextBox("txtname", @ViewData["Location"])
                @Html.ActionLink("Click", "About")
                <fieldset>
                    <legend>Are you Married</legend>
                    @Html.RadioButton("married","yes") Yes
                    @Html.RadioButton("married", "no") no

                </fieldset>
                <fieldset>
                    <legend>Do you Agree</legend>
                    @Html.CheckBox("agree")
                </fieldset>
                <fieldset>
                    <legend>Select Color</legend>
                    @Html.DropDownList("color",listItems,"select color")
                </fieldset>

            </div>
        </div>
    </div>
</div>

MVCTutorials/Views/Test/PartailView1.cshtml
<table class="table table-bordered table-striped">
    <tr>
        <td>Name</td>
        <td>Description</td>
    </tr>
    <tr>
        <td>Student 1</td>
        <td>Test Description</td>
    </tr>
    <tr>
        <td>Student 2</td>
        <td>Test Description</td>
    </tr>
    <tr>
        <td>Student 3</td>
        <td>Test Description</td>
    </tr>
    <tr>
        <td>Student 4</td>
        <td>Test Description</td>
    </tr>
</table>

MVCTutorials/Views/Test/Razor.cshtml
@using MVCTutorials.Models;
@{
    ViewBag.Title = "Razor";
}

@{
    var name = "pragim tech";
    int count = 10;
    string message = "total student count:" + count;
}

<h2>Razor Syntax</h2>

<p>@name</p>
<p>My institution name:@name and @message</p>

<!--   decission block -->

@{
    var result = "";
    bool isAllowed = true;
    if (isAllowed)
    {
        result = "This page was posted using the Submit button.";
    }
    else
    {
        result = "This was the first request for this page.";
    }
}
<p>@result</p>

<!--Markup with Decission-->
@if (isAllowed)
{
    <p>This page was posted using the Submit button.</p>
}
else
{
    <p>This was the first request for this page.</p>
}

<!--Markup with Inline Expression-->

<p>Total students:@(count * 2)</p>

The time is: <br /> @DateTime.Now


@if (isAllowed)
{
    <p>The time is: <br /> @DateTime.Now</p>
    @: The time is: <br /> @DateTime.Now








}

<!--looping -->


@{
    for (int i = 0; i <= 10; i++)
    {
        <p>Loop Count# @i</p>
    }

    string[] names = { "student1", "student2", "student3" };

    foreach (var item in names)
    {
        @item <br />
    }
    // object style = new { style = "background-color:yellow" };

}


@* UL Block using Razor
    using for loop
    declare i variable
*@

<ul>
    @for (int i = 1; i <= 10; i++)
    {
        <li>@i</li>
    }
</ul>

@*HTML Helpers*@
<p>Enter name:<input type="text" name="txtname" value="rama" class="txtStyle" data-name="my name is rama" /></p>

<p>Enter name:@Html.TextBox("txtname", "rama", new { @class = "txtStyle", @data_name = "my namme is rama" })</p>

<p>Enter Description: <textarea id="txtdescription" name="txtdescription" rows="4" cols="25">mvc </textarea></p>

<p>Enter Description:@Html.TextArea("txtdescription", new { rows = "4", cols = "25" })</p>

<p>Gender :<input type="radio" name="gender" />Male  <input type="radio" name="gender" /> Female</p>

<p>Gender:@Html.RadioButton("rgender", "Male")Male  @Html.RadioButton("rgender", "Female") Female </p>

<p>
    Select Color:
    <select>
        <option value="-1">--select color--</option>
        <option value="Red">Red</option>
        <option value="Yellow">Yellow</option>
        <option value="Green">Green</option>
    </select>
</p>
@{
    List<SelectListItem> ddllist = new List<SelectListItem>();
    ddllist.Add(new SelectListItem { Text = "Red", Value = "Red" });
    ddllist.Add(new SelectListItem { Text = "Yellow", Value = "Yellow" });
    ddllist.Add(new SelectListItem { Text = "Green", Value = "Green", Selected = true });
}
<p>
    Select Color:
    @Html.DropDownList("ddlcolor", ddllist, "--select color--")
</p>

<p>Navigate to About Page : <a href="/test/about">Click Here</a> </p>

<p>Navigate to About Page using Razor : @Html.ActionLink("Click Here", "about", "test") </p>

<p>print url : @Url.Action("about", "home")</p>

<label><strong>my name is rama</strong></label>

<label><strong>position : tech architect</strong></label>

<p>Custom HTML Helper : @Html.LabelWithBold("my name is rama")</p>

@*<div width='200px' height='400px' style='background-color:red'>Hi this is red</div>*@

@Html.DivWithBackGround("red")
@Html.DivWithBackGround("yellow")
@Html.DivWithBackGround("green")

@CustomHelper.LabelWithBold("static helper")

@helper LabelWithBoldInline(string content)
{
    <label><strong>@content</strong></label>
}

<p>@LabelWithBoldInline("Inline Helper")</p>

MVCTutorials/Views/Test/Shiva.cshtml
@{
    ViewBag.Title = "Shiva";
}

<h2>om Namo Shivaya</h2>